export const members = [
  {
    id: "kabir-more", name: "Kabir More",
    role: "Co-Founder & Chief Executive Officer (CEO)", shortRole: "Co-Founder & Chief Executive Officer (CEO)",
    tagline: "Founder • Full Stack Developer • Visionary Builder • Problem Solver • Tech Entrepreneur • Helping Startups Grow Through Technology",
    img: "/Team-member-1.jpeg", position: "object-[50%_30%]",
    bio1: "Kabir founded Connect with a vision to create a transparent, performance-driven freelance marketplace that eliminates trust gaps and inefficient hiring systems.",
    bio2: "With strong expertise in product strategy, platform architecture, and marketplace design, he focuses on building scalable systems such as escrow protection, Job Success Score algorithms, and structured workflows that empower both freelancers and businesses globally.",
    philosophy: "\"Build systems that earn trust before demanding it. Every feature should make the next user feel safer than the last.\"",
    location: "Nashik, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "co-founder",
    email: "kabir@connectfreelance.in", resumeUrl: "/KabirMore.pdf", website: "https://kabirmoreportfolio.vercel.app/",
    linkedin: "https://www.linkedin.com/in/kabirr-more-5b2a82355",
    instagram: "https://www.instagram.com/kaabiirrrr.___",
    facebook: "https://www.facebook.com/share/1B8arPCGXZ/",
    github: "https://github.com/kaabiirrrr",
    aiSummary: "Specialized in scalable MERN architecture, fintech payment systems, and premium UI/UX experiences. Rare combination of product thinking and full-stack execution — from trust graph algorithms to bank-grade escrow flows.",
    stats: [{ label: "Components Built", value: 80, suffix: "+" }, { label: "APIs Integrated", value: 25, suffix: "+" }, { label: "Commits", value: 300, suffix: "+" }, { label: "Hours Invested", value: 500, suffix: "+" }],
    skills: [
      { name: "React.js", level: 92, category: "Frontend" }, { name: "JavaScript", level: 93, category: "Frontend" }, { name: "Tailwind CSS", level: 90, category: "Frontend" },
      { name: "Node.js", level: 88, category: "Backend" }, { name: "Express.js", level: 85, category: "Backend" }, { name: "Java", level: 75, category: "Backend" }, { name: "Spring Boot", level: 72, category: "Backend" },
      { name: "Supabase", level: 90, category: "Database" }, { name: "PostgreSQL", level: 80, category: "Database" },
      { name: "UI/UX Design", level: 84, category: "Design" }, { name: "System Design", level: 78, category: "DevOps" }, { name: "Git/GitHub", level: 88, category: "DevOps" },
      { name: "Leadership", level: 90, category: "Leadership & Strategy" }, { name: "Startup Strategy", level: 87, category: "Leadership & Strategy" }, { name: "Product Vision", level: 88, category: "Leadership & Strategy" }, { name: "Team Management", level: 85, category: "Leadership & Strategy" }, { name: "Problem Solving", level: 92, category: "Leadership & Strategy" }, { name: "Business Growth", level: 82, category: "Leadership & Strategy" },
    ],
    contributions: [
      { icon: "🎨", title: "Admin Dashboard", desc: "Full admin panel with analytics, moderation tools, and trust graph visualization.", tag: "UI/UX" },
      { icon: "💳", title: "Escrow Payment System", desc: "Stripe integration with manual capture and atomic fund distribution.", tag: "Backend" },
      { icon: "🔐", title: "Authentication Flow", desc: "Google OAuth + email auth with race-condition-safe profile sync.", tag: "Auth" },
      { icon: "📊", title: "Trust Graph Algorithm", desc: "JSS scoring system, badge priority hierarchy, and relationship intelligence engine.", tag: "Algorithm" },
      { icon: "🚀", title: "Design System", desc: "Neo-Brutalist design tokens, dark/light mode, and premium SaaS component library.", tag: "Frontend" },
      { icon: "🤖", title: "AI Assistant", desc: "AI-powered assistant with context-aware suggestions for freelancers and clients.", tag: "AI/ML" },
    ],
    timeline: [
      { year: "2026", type: "education", title: "Diploma in Information Technology", org: "Government Polytechnic, Nashik", desc: "Pursuing final year with strong focus on software engineering, databases, and full stack development." },
      { year: "2026", type: "internship", title: "Full Stack Developer Intern", org: "ESTPL", desc: "Contributed to building real-world web applications and optimizing user interfaces using modern web technologies." },
      { year: "2025", type: "project", title: "Grahak Bhandar", org: "Full Stack Web Application Project", desc: "Built an inventory management system using HTML, CSS, JavaScript, PHP, and MySQL with features like stock management, sales tracking, and CRUD operations." },
      { year: "2025", type: "project", title: "Predicting Mobile Battery Life", org: "Machine Learning Project", desc: "Developed a battery life prediction model using Python and regression algorithms with real-world data preprocessing and evaluation workflow." },
      { year: "2024", type: "project", title: "Student Management System", org: "Java + MySQL Project", desc: "Created a desktop-based CRUD management system using Java, JDBC, and MySQL for handling student records efficiently." },
      { year: "2024", type: "certification", title: "Full Stack Development Journey", org: "Self-Learning & Skill Development", desc: "Focused on Java, frontend development, backend architecture, Git, databases, and problem-solving through hands-on projects and continuous learning." },
      { year: "2023", type: "education", title: "Diploma Started", org: "Government Polytechnic, Nashik", desc: "Started Diploma in Information Technology with strong academic performance and growing interest in software development." },
      { year: "2023", type: "education", title: "SSC Completed", org: "Bright English Medium School", desc: "Completed SSC with 90.40% and developed a strong foundation in technology and logical thinking." },
    ],
    portfolio: [
      { title: "Connect Freelance", image: "/ConnectFreelance.png", desc: "A comprehensive Freelance platform combining skill showcasing and talent discovery for freelancers and clients.", techStack: "React.js + Node.js + Supabase + Express.js", role: "Co-Founder & Lead Dev", demo: "https://connectfreelance.in", github: "https://github.com/kaabiirrrr/conback" },
      { title: "Grahak Bhandar", image: "/GrahakBhandar.png", desc: "Inventory Management System for College Stationery.", techStack: "React.js + Node.js + PostgreSQL + PHP", role: "Full Stack Developer", demo: null, github: "https://github.com/kaabiirrrr" },
    ],
  },
  {
    id: "rohan-patil", name: "Rohan Patil",
    role: "Co-Founder & Growth Lead", shortRole: "Co-Founder & Growth Lead",
    tagline: "Building trust infrastructure for modern freelance hiring.",
    img: "/WhatsApp Image 2026-05-20 at 10.51.46.jpeg", position: "object-[50%_20%]",
    bio1: "Rohan focuses on growth, user acquisition, SEO, content systems, and startup positioning at Connect Freelance.",
    bio2: "He works on improving platform visibility, freelancer onboarding, brand strategy, and scalable marketing systems while helping build a trust-first freelance ecosystem.",
    philosophy: "\"Growth without trust creates noise. Sustainable platforms need both.\"",
    location: "Jalgaon, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "growth-lead",
    email: "rohan@connectfreelance.in", resumeUrl: null, website: "https://therohanpatil.vercel.app/",
    linkedin: "https://www.linkedin.com/in/rohan-patil-248aaa2a3/",
    instagram: "https://www.instagram.com/rohanpatil.3104/",
    facebook: "https://www.facebook.com/rohanpatil.3104",
    github: "https://github.com/rohanpatil-15",
    aiSummary: "Growth-focused builder working on user acquisition, SEO systems, brand positioning, and marketplace expansion for Connect Freelance. Focused on building scalable trust-first hiring infrastructure.",
    stats: [
      { label: "Campaigns Worked On", value: 5, suffix: "+" },
      { label: "Users Reached Organically", value: 100, suffix: "+" },
      { label: "Content Assets Published", value: 20, suffix: "+" },
      { label: "Platforms Managed", value: 4, suffix: "" }
    ],
    skills: [
      // Growth
      { name: "SEO / Search Visibility", level: 82, category: "Growth" },
      { name: "Content Strategy", level: 86, category: "Growth" },
      { name: "Social Media Growth", level: 78, category: "Growth" },
      { name: "Brand Positioning", level: 84, category: "Growth" },
      // Product
      { name: "User Acquisition", level: 80, category: "Product" },
      { name: "Growth Systems", level: 76, category: "Product" },
      { name: "Onboarding Flows", level: 74, category: "Product" },
      { name: "Marketplace Strategy", level: 72, category: "Product" },
      // Technical Understanding
      { name: "Frontend Systems", level: 65, category: "Technical Understanding" },
      { name: "Analytics", level: 70, category: "Technical Understanding" },
      { name: "Platform Architecture", level: 60, category: "Technical Understanding" },
      { name: "API Understanding", level: 58, category: "Technical Understanding" },
    ],
    skillsTags: [
      "Growth Strategy",
      "SEO",
      "Product Marketing",
      "Content Systems",
      "Brand Positioning",
      "Community Growth",
      "Startup Operations"
    ],
    contributions: [
      { icon: "📣", title: "Go-To-Market Strategy", desc: "Built the initial GTM strategy including positioning, onboarding systems, SEO planning, and platform visibility workflows.", tag: "Growth" },
      { icon: "🔍", title: "SEO Infrastructure", desc: "Worked on technical SEO, structured content planning, profile indexing, and search visibility optimization.", tag: "Growth" },
      { icon: "📱", title: "Social Media Systems", desc: "Managing brand visibility across LinkedIn, X, Instagram, Medium, and Dev.to through consistent startup-focused content.", tag: "Growth" },
      { icon: "🎯", title: "User Acquisition", desc: "Focused on organic acquisition systems, audience targeting, onboarding optimization, and growth experimentation.", tag: "Product" },
      { icon: "✨", title: "Brand Positioning", desc: "Helping position Connect Freelance as a trust-focused freelance infrastructure platform instead of another bidding marketplace.", tag: "Product" },
    ],
    timeline: [
      { year: "2026", type: "project", title: "Connect Freelance", org: "Co-Founder & Growth Lead", desc: "Leading growth strategy, SEO, content systems, and marketplace user acquisition." },
      { year: "2025", type: "project", title: "Personal Brand Building", org: "Startup Content Systems", desc: "Started building startup-focused content systems across multiple platforms." },
      { year: "2025", type: "education", title: "Information Technology Diploma", org: "Government Polytechnic Nashik", desc: "Completed diploma with focus on computing, database foundations, and information technology." },
    ],
    portfolio: [
      { title: "Connect Freelance GTM", desc: "Built growth strategy, SEO direction, onboarding flows, and social visibility systems for Connect Freelance.", techStack: "Strategy + Analytics", role: "Co-Founder & Growth Lead", demo: "https://connectfreelance.in", github: null },
      { title: "Startup Content Systems", desc: "Building content distribution across LinkedIn, X, Medium, Dev.to, and startup communities.", techStack: "Content + Social", role: "Co-Founder & Growth Lead", demo: null, github: null },
      { title: "SEO & Visibility", desc: "Working on search indexing, structured profiles, backlinks, metadata optimization, and discoverability systems.", techStack: "SEO + Marketing", role: "Co-Founder & Growth Lead", demo: null, github: null },
    ],
  },
  {
    id: "samarth-shendge", name: "Samarth Shendge",
    role: "Chief Technology Officer (CTO)", shortRole: "Chief Technology Officer",
    tagline: "Backend Architect · API Expert · System Design",
    img: "/Team-member-3.jpeg", position: "object-[50%_10%]",
    bio1: "Samarth leads the technical vision of Connect, ensuring the platform is robust, scalable, and performance-driven.",
    bio2: "With strong expertise in full-stack development, system design, and cloud-based architecture, he solves critical challenges — API optimization, authentication security, and performance tuning.",
    philosophy: "\"Reliability is not a feature — it's the foundation. Every system must degrade gracefully and recover faster.\"",
    location: "Pune, Maharashtra, India", experience: "2+", availability: "busy", badgeType: "cto",
    email: "samarth@connectfreelance.in", resumeUrl: null,
    linkedin: "https://www.linkedin.com/in/samarth-shendge-166ba1354",
    instagram: "https://www.instagram.com/samarth_shendge_20/",
    facebook: "https://m.facebook.com/profile.php?id=61578606565247",
    github: "https://github.com/samarthshendge20-tech",
    aiSummary: "Expert in Node.js microservice architecture, PostgreSQL optimization, and REST API design. Builds systems that scale to thousands of concurrent users with zero downtime.",
    stats: [{ label: "APIs Built", value: 40, suffix: "+" }, { label: "DB Tables Designed", value: 30, suffix: "+" }, { label: "Commits", value: 250, suffix: "+" }, { label: "Uptime Achieved", value: 99, suffix: "%" }],
    skills: [
      { name: "Node.js", level: 93, category: "Backend" }, { name: "Express.js", level: 91, category: "Backend" }, { name: "REST APIs", level: 92, category: "Backend" },
      { name: "PostgreSQL", level: 90, category: "Database" }, { name: "Supabase", level: 88, category: "Database" },
      { name: "System Design", level: 85, category: "DevOps" }, { name: "Git/GitHub", level: 87, category: "DevOps" },
      { name: "React.js", level: 75, category: "Frontend" },
    ],
    contributions: [
      { icon: "⚙️", title: "Backend Architecture", desc: "Full Node.js/Express backend with modular handlers, middleware layers, and error boundaries.", tag: "Backend" },
      { icon: "🔑", title: "Authentication System", desc: "JWT auth, refresh token rotation, Google OAuth, and secure session management.", tag: "Auth" },
      { icon: "📡", title: "API Optimization", desc: "Optimized 40+ endpoints for sub-200ms response using query tuning and connection pooling.", tag: "Backend" },
      { icon: "🗄️", title: "Database Schema Design", desc: "Full PostgreSQL schema — RLS policies, indexes, and Supabase realtime subscriptions.", tag: "Algorithm" },
      { icon: "🛡️", title: "Security Hardening", desc: "Rate limiting, input sanitization, CORS policies, and fraud detection across all endpoints.", tag: "Backend" },
    ],
    timeline: [
      { year: "2025", type: "project", title: "Connect Freelance", org: "Chief Technology Officer", desc: "Owns the entire backend infrastructure and API layer of the platform." },
      { year: "2024", type: "internship", title: "Backend Developer Intern", org: "Engeniuspark Technologies", desc: "Built server-side modules and REST APIs for the Refuel EV management system." },
      { year: "2024", type: "education", title: "Diploma in Computer Science", org: "Government Polytechnic", desc: "Focused on data structures, algorithms, and database management systems." },
      { year: "2024", type: "certification", title: "Node.js Advanced Patterns", org: "Self-Study", desc: "Mastered streams, clustering, and production-grade Node.js patterns." },
    ],
    portfolio: [
      { title: "Connect Freelance API", desc: "40+ endpoint REST API — auth, jobs, proposals, contracts, payments, and realtime notifications.", techStack: "Node.js + PostgreSQL + Supabase", role: "Backend Lead", demo: null, github: "https://github.com/samarthshendge20-tech" },
      { title: "Refuel Backend", desc: "Real-time queue management API with station tracking and admin reporting.", techStack: "Node.js + Express", role: "Backend Developer", demo: null, github: null },
    ],
  },
  {
    id: "vijay-biradar", name: "Vijay Biradar",
    role: "Chief Product Officer (CPO)", shortRole: "Chief Product Officer",
    tagline: "Product Strategist · UX Researcher · Feature Designer",
    img: "/Team-member-4.png", position: "object-[50%_25%]",
    bio1: "Vijay drives the product strategy of Connect, focusing on creating a seamless and user-friendly experience for both clients and freelancers.",
    bio2: "With a deep understanding of user behavior and product design, he works closely with the development team to refine features like profile completion, job posting, and bidding systems.",
    philosophy: "\"A great product solves a problem users didn't know they had, in a way they didn't expect, but immediately love.\"",
    location: "Pune, Maharashtra, India", experience: "2+", availability: "busy", badgeType: "cpo",
    email: "vijay@connectfreelance.in", resumeUrl: null,
    linkedin: "https://www.linkedin.com/in/vijay-biradar-02b7a7352",
    instagram: "https://www.instagram.com/vijaybiradar2022/",
    facebook: "https://www.facebook.com/share/1HtU1kHSSt/",
    github: "https://github.com/vijaybiradar1508-rgb",
    aiSummary: "Expert in product roadmapping, user journey mapping, and feature prioritization. Bridges the gap between user needs and technical feasibility — ensuring every release adds measurable value.",
    stats: [{ label: "Features Shipped", value: 30, suffix: "+" }, { label: "User Flows Mapped", value: 20, suffix: "+" }, { label: "Wireframes Created", value: 60, suffix: "+" }, { label: "A/B Tests Run", value: 10, suffix: "+" }],
    skills: [
      { name: "Product Strategy", level: 91, category: "Frontend" }, { name: "User Research", level: 88, category: "Frontend" },
      { name: "Wireframing", level: 85, category: "Design" }, { name: "Figma", level: 83, category: "Design" },
      { name: "Analytics", level: 80, category: "Backend" }, { name: "Roadmapping", level: 87, category: "Backend" },
      { name: "React.js", level: 72, category: "DevOps" }, { name: "SQL", level: 70, category: "Database" },
    ],
    contributions: [
      { icon: "🗺️", title: "Product Roadmap", desc: "Full feature roadmap from MVP to V2 — trust features, payment flows, and onboarding.", tag: "Product" },
      { icon: "🔍", title: "User Research", desc: "User interviews and usability testing validating the bidding system and profile wizard.", tag: "Product" },
      { icon: "📋", title: "Feature Specifications", desc: "Detailed PRDs and acceptance criteria for every major feature across both dashboards.", tag: "Product" },
      { icon: "🔄", title: "Onboarding Flow", desc: "Multi-step profile wizard for freelancers and clients, improving completion rates significantly.", tag: "UI/UX" },
      { icon: "📐", title: "UI Wireframes", desc: "Wireframes and prototypes for all core pages — dashboard, job board, and proposal views.", tag: "Design" },
    ],
    timeline: [
      { year: "2025", type: "project", title: "Connect Freelance", org: "Chief Product Officer", desc: "Owns product strategy, feature prioritization, and the full user experience roadmap." },
      { year: "2024", type: "internship", title: "Product Design Intern", org: "Engeniuspark Technologies", desc: "Designed UI screens and user flows for the Refuel EV management system." },
      { year: "2024", type: "education", title: "Diploma in CS/Design", org: "Government Polytechnic", desc: "Studied human-computer interaction, UX principles, and software project management." },
      { year: "2024", type: "certification", title: "Product Management", org: "Self-Study", desc: "Completed Agile, sprint planning, and OKR fundamentals." },
    ],
    portfolio: [
      { title: "Connect Freelance Product", desc: "Full product design — roadmap, wireframes, user flows, and feature specifications.", techStack: "Figma + Strategy", role: "Chief Product Officer", demo: "https://connectfreelance.in", github: null },
      { title: "Onboarding Wizard", desc: "5-step profile completion wizard with progress tracking and skill tagging.", techStack: "React + UX Design", role: "Product Designer", demo: null, github: null },
    ],
  },
  {
    id: "vaibhav-pawar", name: "Vaibhav Pawar",
    role: "Chief Operations Officer (COO)", shortRole: "Chief Operations Officer",
    tagline: "Operations Lead · QA Engineer · Platform Stability",
    img: "/Team-member-5.jpeg", position: "object-[50%_35%]",
    bio1: "Vaibhav oversees the operational flow of Connect, ensuring that all components of the platform work together smoothly and efficiently.",
    bio2: "He plays a crucial role in testing, quality assurance, and overall system coordination, helping maintain stability, reliability, and consistency throughout the platform.",
    philosophy: "\"Quality is not an act — it's a habit. Ship it only when you'd stake your reputation on it.\"",
    location: "Pune, Maharashtra, India", experience: "2+", availability: "busy", badgeType: "coo",
    email: "vaibhav@connectfreelance.in", resumeUrl: null,
    linkedin: "https://www.linkedin.com/in/vaibhav-pawar-3122023b3",
    instagram: "https://www.instagram.com/vaibhav_pawar.96.k",
    facebook: "https://www.facebook.com/share/1BKKwq8ZNQ/",
    github: "https://github.com/vaibhavdpawar9921-Tech",
    aiSummary: "Expert in end-to-end testing, quality assurance workflows, and platform coordination. Ensures zero critical bugs reach production through robust regression suites and systematic validation.",
    stats: [{ label: "Bugs Caught", value: 120, suffix: "+" }, { label: "Test Cases Written", value: 80, suffix: "+" }, { label: "Deployments Managed", value: 50, suffix: "+" }, { label: "Processes Built", value: 15, suffix: "+" }],
    skills: [
      { name: "Quality Assurance", level: 92, category: "DevOps" }, { name: "Manual Testing", level: 90, category: "DevOps" }, { name: "Deployment", level: 85, category: "DevOps" },
      { name: "Process Design", level: 88, category: "Backend" }, { name: "Bug Tracking", level: 87, category: "Backend" },
      { name: "React.js", level: 72, category: "Frontend" }, { name: "Node.js", level: 70, category: "Frontend" },
      { name: "SQL", level: 75, category: "Database" },
    ],
    contributions: [
      { icon: "🧪", title: "QA Test Suite", desc: "Full manual regression suite covering auth, payments, proposals, and messaging flows.", tag: "QA" },
      { icon: "🚀", title: "Deployment Pipeline", desc: "All production deployments to Render and Vercel — zero-downtime with rollback strategies.", tag: "DevOps" },
      { icon: "🐛", title: "Bug Triage System", desc: "Bug reporting workflow, severity classification, and resolution tracking system.", tag: "QA" },
      { icon: "📋", title: "Operations Coordination", desc: "Cross-team communication, sprint reviews, and platform incident response.", tag: "Product" },
      { icon: "📊", title: "Performance Monitoring", desc: "Platform monitoring, uptime checks, and alert systems ensuring 99%+ reliability.", tag: "Backend" },
    ],
    timeline: [
      { year: "2025", type: "project", title: "Connect Freelance", org: "Chief Operations Officer", desc: "Owns platform stability, QA processes, deployment coordination, and team operations." },
      { year: "2024", type: "internship", title: "QA & Operations Intern", org: "Engeniuspark Technologies", desc: "Testing and deployment coordination for the Refuel EV management platform." },
      { year: "2024", type: "education", title: "Diploma in Computer Science", org: "Government Polytechnic", desc: "Studied software testing methodologies and IT operations." },
      { year: "2024", type: "certification", title: "Software Testing Basics", org: "Self-Study", desc: "Mastered test case design, black-box testing, and defect lifecycle management." },
    ],
    portfolio: [
      { title: "Connect Freelance Ops", desc: "QA pipeline, deployment workflow, monitoring stack, and incident response protocol.", techStack: "QA + DevOps", role: "Chief Operations Officer", demo: "https://connectfreelance.in", github: null },
      { title: "Regression Test Suite", desc: "120+ test cases covering critical user journeys — auth, payments, proposals, and contracts.", techStack: "Manual + Documented", role: "QA Lead", demo: null, github: null },
    ],
  },
];
