export const members = [
  {
    id: "kabir-more", name: "Kabir More",
    role: "Co-Founder & Chief Executive Officer (CEO)", shortRole: "Co-Founder & Chief Executive Officer (CEO)",
    tagline: "Founder • Full Stack Developer • Visionary Builder • Problem Solver • Tech Entrepreneur • Helping Startups Grow Through Technology",
    img: "/Team-member-1.jpeg", position: "object-[50%_30%]",
    bio1: "Kabir founded Connect with a vision to create a transparent, performance-driven freelance marketplace that eliminates trust gaps and inefficient hiring systems.",
    bio2: "With strong expertise in product strategy, platform architecture, and marketplace design, he focuses on building scalable systems such as escrow protection, Job Success Score algorithms, and structured workflows that empower both freelancers and businesses globally.",
    philosophy: "\"Build systems that earn trust before demanding it. Every feature should make the next user feel safer than the last.\"",
    location: "Nashik, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "co-founder",
    email: "kabirmore8904@gmail.com", resumeUrl: "/KabirMore.pdf", website: "https://connectfreelance.in",
    profile: "https://connectfreelance.in/about/team/kabir-more",
    github: "https://github.com/kaabiirrrr",
    linkedin: "https://linkedin.com/in/kabirr-more-5b2a82355",
    twitter: "https://x.com/SKIMMER2160",
    instagram: "https://instagram.com/kaabiirrrr.___",
    facebook: "https://www.facebook.com/share/1B8arPCGXZ/",
    medium: "https://medium.com/@kabirmore8904",
    devto: "https://dev.to/kaabiirrrr",
    producthunt: "https://www.producthunt.com/@if_more_kabir_ashok",
    aiSummary: "Specialized in scalable MERN architecture, fintech payment systems, and premium UI/UX experiences. Rare combination of product thinking and full-stack execution — from trust graph algorithms to bank-grade escrow flows.",
    stats: [{ label: "Components Built", value: 80, suffix: "+" }, { label: "APIs Integrated", value: 25, suffix: "+" }, { label: "Commits", value: 300, suffix: "+" }, { label: "Hours Invested", value: 500, suffix: "+" }],
    skills: [
      { name: "React.js", level: 92, category: "Frontend" }, { name: "JavaScript", level: 93, category: "Frontend" }, { name: "Tailwind CSS", level: 90, category: "Frontend" },
      { name: "Node.js", level: 88, category: "Backend" }, { name: "Express.js", level: 85, category: "Backend" }, { name: "Java", level: 75, category: "Backend" }, { name: "Spring Boot", level: 72, category: "Backend" },
      { name: "Supabase", level: 90, category: "Database" }, { name: "PostgreSQL", level: 80, category: "Database" },
      { name: "UI/UX Design", level: 84, category: "Design" }, { name: "System Design", level: 78, category: "DevOps" }, { name: "Git/GitHub", level: 88, category: "DevOps" },
      { name: "Leadership", level: 90, category: "Leadership & Strategy" }, { name: "Startup Strategy", level: 87, category: "Leadership & Strategy" }, { name: "Product Vision", level: 88, category: "Leadership & Strategy" }, { name: "Team Management", level: 85, category: "Leadership & Strategy" }, { name: "Problem Solving", level: 92, category: "Leadership & Strategy" }, { name: "Business Growth", level: 82, category: "Leadership & Strategy" },
    ],
    contributions: [
      { icon: "🎨", title: "Admin Dashboard", desc: "Full admin panel with analytics, moderation tools, and trust graph visualization.", tag: "UI/UX" },
      { icon: "💳", title: "Escrow Payment System", desc: "Stripe integration with manual capture and atomic fund distribution.", tag: "Backend" },
      { icon: "🔐", title: "Authentication Flow", desc: "Google OAuth + email auth with race-condition-safe profile sync.", tag: "Auth" },
      { icon: "📊", title: "Trust Graph Algorithm", desc: "JSS scoring system, badge priority hierarchy, and relationship intelligence engine.", tag: "Algorithm" },
      { icon: "🚀", title: "Design System", desc: "Neo-Brutalist design tokens, dark/light mode, and premium SaaS component library.", tag: "Frontend" },
      { icon: "🤖", title: "AI Assistant", desc: "AI-powered assistant with context-aware suggestions for freelancers and clients.", tag: "AI/ML" },
    ],
    timeline: [
      { year: "2026", type: "education", title: "Diploma in Information Technology", org: "Government Polytechnic, Nashik", desc: "Pursuing final year with strong focus on software engineering, databases, and full stack development." },
      { year: "2026", type: "internship", title: "Full Stack Developer Intern", org: "ESTPL", desc: "Contributed to building real-world web applications and optimizing user interfaces using modern web technologies." },
      { year: "2025", type: "project", title: "Grahak Bhandar", org: "Full Stack Web Application Project", desc: "Built an inventory management system using HTML, CSS, JavaScript, PHP, and MySQL with features like stock management, sales tracking, and CRUD operations." },
      { year: "2025", type: "project", title: "Predicting Mobile Battery Life", org: "Machine Learning Project", desc: "Developed a battery life prediction model using Python and regression algorithms with real-world data preprocessing and evaluation workflow." },
      { year: "2024", type: "project", title: "Student Management System", org: "Java + MySQL Project", desc: "Created a desktop-based CRUD management system using Java, JDBC, and MySQL for handling student records efficiently." },
      { year: "2024", type: "certification", title: "Full Stack Development Journey", org: "Self-Learning & Skill Development", desc: "Focused on Java, frontend development, backend architecture, Git, databases, and problem-solving through hands-on projects and continuous learning." },
      { year: "2023", type: "education", title: "Diploma Started", org: "Government Polytechnic, Nashik", desc: "Started Diploma in Information Technology with strong academic performance and growing interest in software development." },
      { year: "2023", type: "education", title: "SSC Completed", org: "Bright English Medium School", desc: "Completed SSC with 90.40% and developed a strong foundation in technology and logical thinking." },
    ],
    portfolio: [
      { title: "Connect Freelance", image: "/ConnectFreelance.png", desc: "A comprehensive Freelance platform combining skill showcasing and talent discovery for freelancers and clients.", techStack: "React.js + Node.js + Supabase + Express.js", role: "Co-Founder & Lead Dev", demo: "https://connectfreelance.in", github: "https://github.com/kaabiirrrr/conback" },
      { title: "Grahak Bhandar", image: "/GrahakBhandar.png", desc: "Inventory Management System for College Stationery.", techStack: "React.js + Node.js + PostgreSQL + PHP", role: "Full Stack Developer", demo: null, github: "https://github.com/kaabiirrrr" },
      { title: "Apple Clone Website", image: "/AppleClone.png", desc: "A high-fidelity replica of the Apple Store website featuring smooth animations and a premium UI experience. Built to demonstrate advanced frontend layout and styling techniques.", techStack: "React.js + Tailwind CSS", role: "Frontend Developer", demo: null, github: "https://github.com/kaabiirrrr" },
      { title: "E commerce Website", image: "/EcommerceWebsite.png", desc: "A full-featured digital storefront with a modern product catalog, responsive shopping cart, and secure checkout flow. Optimized for seamless user experience across all devices.", techStack: "React.js + Node.js + MongoDB", role: "Full Stack Developer", demo: null, github: "https://github.com/kaabiirrrr" },
    ],
  },
  {
    id: "rohan-patil", name: "Rohan Patil",
    role: "Co-Founder & Chief Growth Lead Officer (CGO)", shortRole: "Co-Founder & Chief Growth Lead Officer (CGO)",
    tagline: "Building trust infrastructure for modern freelance hiring.",
    img: "/WhatsApp Image 2026-05-20 at 10.51.46.jpeg", position: "object-[50%_20%]",
    bio1: "Rohan focuses on growth, user acquisition, SEO, content systems, and startup positioning at Connect Freelance.",
    bio2: "He works on improving platform visibility, freelancer onboarding, brand strategy, and scalable marketing systems while helping build a trust-first freelance ecosystem.",
    philosophy: "\"Growth without trust creates noise. Sustainable platforms need both.\"",
    location: "Jalgaon, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "cgo",
    email: "rohanyp1592007@gmail.com", resumeUrl: null, website: "https://connectfreelance.in",
    profile: "https://connectfreelance.in/about/rohan-patil",
    linkedin: "https://linkedin.com/in/therohanpatil15",
    instagram: "https://instagram.com/therohanpatil15",
    twitter: "https://x.com/therohanpatil15",
    medium: "https://medium.com/@rohanyp1592007",
    devto: "https://dev.to/therohanpatil15",
    producthunt: "https://www.producthunt.com/@therohanpatil15",
    github: "https://github.com/therohanpatil15",
    aiSummary: "Growth-focused builder working on user acquisition, SEO systems, brand positioning, and marketplace expansion for Connect Freelance. Focused on building scalable trust-first hiring infrastructure.",
    stats: [
      { label: "Campaigns Worked On", value: 5, suffix: "+" },
      { label: "Users Reached Organically", value: 100, suffix: "+" },
      { label: "Content Assets Published", value: 20, suffix: "+" },
      { label: "Platforms Managed", value: 4, suffix: "" }
    ],
    skills: [
      // Growth
      { name: "SEO / Search Visibility", level: 82, category: "Growth" },
      { name: "Content Strategy", level: 86, category: "Growth" },
      { name: "Social Media Growth", level: 78, category: "Growth" },
      { name: "Brand Positioning", level: 84, category: "Growth" },
      // Product
      { name: "User Acquisition", level: 80, category: "Product" },
      { name: "Growth Systems", level: 76, category: "Product" },
      { name: "Onboarding Flows", level: 74, category: "Product" },
      { name: "Marketplace Strategy", level: 72, category: "Product" },
      // Technical Understanding
      { name: "Frontend Systems", level: 65, category: "Technical Understanding" },
      { name: "Analytics", level: 70, category: "Technical Understanding" },
      { name: "Platform Architecture", level: 60, category: "Technical Understanding" },
      { name: "API Understanding", level: 58, category: "Technical Understanding" },
    ],
    skillsTags: [
      "Growth Strategy",
      "SEO",
      "Product Marketing",
      "Content Systems",
      "Brand Positioning",
      "Community Growth",
      "Startup Operations"
    ],
    contributions: [
      { icon: "📣", title: "Go-To-Market Strategy", desc: "Built the initial GTM strategy including positioning, onboarding systems, SEO planning, and platform visibility workflows.", tag: "Growth" },
      { icon: "🔍", title: "SEO Infrastructure", desc: "Worked on technical SEO, structured content planning, profile indexing, and search visibility optimization.", tag: "Growth" },
      { icon: "📱", title: "Social Media Systems", desc: "Managing brand visibility across LinkedIn, X, Instagram, Medium, and Dev.to through consistent startup-focused content.", tag: "Growth" },
      { icon: "🎯", title: "User Acquisition", desc: "Focused on organic acquisition systems, audience targeting, onboarding optimization, and growth experimentation.", tag: "Product" },
      { icon: "✨", title: "Brand Positioning", desc: "Helping position Connect Freelance as a trust-focused freelance infrastructure platform instead of another bidding marketplace.", tag: "Product" },
    ],
    timeline: [
      { year: "2026", type: "project", title: "Connect Freelance", org: "Co-Founder & Chief Growth Lead Officer (CGO)", desc: "Leading growth strategy, SEO, content systems, and marketplace user acquisition." },
      { year: "2025", type: "project", title: "Personal Brand Building", org: "Startup Content Systems", desc: "Started building startup-focused content systems across multiple platforms." },
      { year: "2025", type: "education", title: "Information Technology Diploma", org: "Government Polytechnic Nashik", desc: "Completed diploma with focus on computing, database foundations, and information technology." },
    ],
    portfolio: [
      { title: "Connect Freelance GTM", image: "/ConnectFreelance.png", desc: "Built growth strategy, SEO direction, onboarding flows, and social visibility systems for Connect Freelance.", techStack: "Strategy + Analytics", role: "Co-Founder & Chief Growth Lead Officer (CGO)", demo: "https://connectfreelance.in", github: null },
      { title: "Hidden Cafe", image: "/HiddenCafe.png", desc: "Designed and built a full restaurant website for Hidden Cafe — a real Nashik-based dining brand. Focused on atmosphere and driving table reservations.", techStack: "React + Tailwind + Framer", role: "Full Stack Developer", demo: "https://hiddencafe.vercel.app/", github: null },
      { title: "Mehfil The Cafe", image: "/MehfilCafe.png", desc: "Built the complete web presence for Mehfil The Cafe — a premium cafe brand. The site captures the warmth and aesthetic of the physical space.", techStack: "React + Tailwind + Framer", role: "Full Stack Developer", demo: "https://mehfilethecafe.vercel.app/", github: null },
      { title: "Grahak Bhandar", image: "/GrahakBhandarRohan.png", desc: "A comprehensive collegiate inventory system engineered to manage stock dynamically. Digitized manual entry logs and reduced operational overhead.", techStack: "PHP + JS + MySQL", role: "Full Stack Developer", demo: "https://grahakbhandar.rf.gd/dashboard.php", github: null }
    ],
  },
  {
    id: "samarth-shendge", name: "Samarth Shendge",
    role: "Chief Technology Officer (CTO)", shortRole: "Chief Technology Officer",
    tagline: "Building scalable systems and trust-driven infrastructure for modern freelance hiring.",
    img: "/Team-member-3.jpeg", position: "object-[90%_0%]",
    bio1: "Focused on scalable platform engineering, MERN-stack architecture, real-time systems, frontend performance, backend infrastructure, and modern freelance marketplace development for Connect Freelance.",
    bio2: "Samarth leads the technical architecture and engineering systems at Connect Freelance. He focuses on frontend engineering, backend infrastructure, real-time messaging systems, scalable database design, freelancer workflows, job systems, and platform performance optimization.",
    philosophy: "\"Strong products are built when engineering, trust, and user experience scale together.\"",
    location: "Beed, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "cto",
    email: "samarth@connectfreelance.in", resumeUrl: "/MYRESUME.pdf",
    linkedin: "https://www.linkedin.com/in/samarth-shendge-166ba1354",
    instagram: "https://www.instagram.com/samarth_shendge_20/",
    facebook: "https://m.facebook.com/profile.php?id=61578606565247",
    github: "https://github.com/samarthshendge20-tech",
    aiSummary: "Technology-focused builder working on scalable freelance infrastructure, backend architecture, real-time systems, database optimization, and modern MERN-stack workflows for Connect Freelance. Focused on building reliable, secure, and performance-driven hiring infrastructure with scalable engineering systems.",
    stats: [{ label: "Projects Developed", value: 5, suffix: "+" }, { label: "Platform Features Built", value: 15, suffix: "+" }, { label: "Frontend Interfaces Designed", value: 10, suffix: "+" }, { label: "Core Systems Managed", value: 4, suffix: "" }],
    skills: [
      { name: "React.js", level: 88, category: "Frontend Engineering" }, { name: "Responsive UI", level: 84, category: "Frontend Engineering" }, { name: "Dashboard Dev", level: 82, category: "Frontend Engineering" }, { name: "Animation & UX", level: 78, category: "Frontend Engineering" },
      { name: "Node.js", level: 85, category: "Backend Engineering" }, { name: "Express.js", level: 82, category: "Backend Engineering" }, { name: "REST APIs", level: 80, category: "Backend Engineering" }, { name: "Auth Systems", level: 79, category: "Backend Engineering" },
      { name: "MongoDB", level: 83, category: "Database & Infra" }, { name: "Database Design", level: 78, category: "Database & Infra" }, { name: "Real-Time Systems", level: 75, category: "Database & Infra" }, { name: "Performance Opt", level: 72, category: "Database & Infra" },
    ],
    contributions: [
      { icon: "⚙️", title: "Platform Architecture", desc: "Designed and developed scalable frontend and backend architecture for Connect Freelance using the MERN stack.", tag: "Architecture" },
      { icon: "💬", title: "Real-Time Messaging System", desc: "Built and optimized real-time messaging workflows, chat systems, and communication infrastructure for freelancers and clients.", tag: "Real-Time" },
      { icon: "🔐", title: "Authentication & Security", desc: "Implemented authentication systems, protected routes, role-based access control, and secure database workflows.", tag: "Security" },
      { icon: "📊", title: "Freelancer Dashboard Systems", desc: "Developed freelancer dashboards, account management systems, profile workflows, and account health infrastructure.", tag: "Frontend" },
      { icon: "🗄️", title: "Database & API Engineering", desc: "Worked on scalable MongoDB structures, REST APIs, optimized queries, and backend integrations for platform performance.", tag: "Backend" },
    ],
    timeline: [
      { year: "2026", type: "project", title: "Connect Freelance", org: "Chief Technology Officer (CTO)", desc: "Leading platform engineering, frontend architecture, backend systems, real-time infrastructure, and scalable freelance marketplace development." },
      { year: "2025", type: "project", title: "Perfect Home", org: "Full Stack Real Estate Platform Project", desc: "Developed a real-estate web platform inspired by 99acres for online property discovery, listing management, and home purchasing workflows." },
      { year: "2025", type: "project", title: "Fake Spam Review Detection", org: "Machine Learning Project", desc: "Built a machine learning model for detecting fake and spam product reviews using NLP preprocessing and classification algorithms." },
      { year: "2025", type: "internship", title: "Engeniuspark Technologies Pvt. Ltd.", org: "MERN Stack Intern", desc: "Worked on full-stack web development using MongoDB, Express.js, React.js, and Node.js. Contributed to real-world application development, API integration, responsive frontend systems, backend workflows, authentication systems, and database operations." },
      { year: "2024-26", type: "education", title: "Diploma in Information Technology", org: "Government Polytechnic Nashik", desc: "Focused on software engineering, web development, database systems, programming, and scalable application development." },
      { year: "2024", type: "certification", title: "Full Stack Development Journey", org: "Self Learning & Skill Development", desc: "Built multiple practical projects while continuously improving development and problem-solving skills in MERN stack and Java." },
      { year: "2023", type: "education", title: "SSC Completed", org: "94.60% Percentage", desc: "Started exploring programming, web development, and technology systems after building a strong academic foundation." },
    ],
    portfolio: [
      { title: "Connect Freelance Platform", image: "/ConnectFreelance.png", desc: "Building scalable freelance marketplace infrastructure with frontend systems, backend architecture, authentication, dashboards, and real-time messaging.", techStack: "MERN Stack", role: "CTO", demo: "https://connectfreelance.in", github: null },
      { title: "Spotify UI Clone", image: "/SpotifyCloneSamarth.jpeg", desc: "A Spotify-inspired multi-page music streaming UI clone built with a dark theme, green accents, and smooth navigation across Home, About, Playlists, and Contact pages.", techStack: "React.js + Tailwind CSS", role: "Frontend Developer", demo: null, github: null },
      { title: "CineSearch", image: "/CineSearchSamarth.jpeg", desc: "A full-stack movie search application that fetches real-time movie data from the OMDb public API and displays titles, posters, ratings, cast, plot, and awards through a clean dark-themed React interface.", techStack: "React.js + Node.js + Express", role: "Full Stack Developer", demo: null, github: null },
    ],
  },
  {
    id: "vijay-biradar", name: "Vijay Biradar",
    role: "Chief Product Officer (CPO)", shortRole: "Chief Product Officer",
    tagline: "Leading product strategy, platform experience, UI/UX systems, and full-stack product execution.",
    img: "/Team-member-4.png", position: "object-[50%_30%]",
    bio1: "Leading product strategy, platform experience, UI/UX systems, and full-stack product execution for Connect Freelance.",
    bio2: "Focused on building a trusted freelance ecosystem with scalable workflows, modern interfaces, and seamless user experiences.",
    philosophy: "\"A great product solves a problem users didn't know they had, in a way they didn't expect, but immediately love.\"",
    location: "Latur, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "cpo",
    email: "vijay@connectfreelance.in", resumeUrl: null,
    linkedin: "https://www.linkedin.com/in/vijay-biradar-02b7a7352",
    instagram: "https://www.instagram.com/vijaybiradar2022/",
    facebook: "https://www.facebook.com/share/1HtU1kHSSt/",
    github: "https://github.com/vijaybiradar1508-rgb",
    aiSummary: "Leading product strategy, platform experience, UI/UX systems, and full-stack product execution for Connect Freelance. Focused on building a trusted freelance ecosystem with scalable workflows, modern interfaces, and seamless user experiences.",
    stats: [{ label: "Features Shipped", value: 30, suffix: "+" }, { label: "User Flows Mapped", value: 20, suffix: "+" }, { label: "Wireframes Created", value: 60, suffix: "+" }, { label: "A/B Tests Run", value: 10, suffix: "+" }],
    skills: [
      { name: "Product Architecture", level: 91, category: "Product" }, { name: "UI/UX Systems", level: 88, category: "Design" },
      { name: "Frontend Design", level: 85, category: "Frontend" }, { name: "React.js", level: 83, category: "Frontend" },
      { name: "Workflow Planning", level: 80, category: "Product" }, { name: "Automation Integration", level: 87, category: "Backend" },
      { name: "Node.js", level: 72, category: "Backend" }, { name: "System Scalability", level: 70, category: "Architecture" },
    ],
    contributions: [
      { icon: "🗺️", title: "Product Architecture", desc: "Product architecture & workflow planning for Connect Freelance.", tag: "Product" },
      { icon: "🎨", title: "Frontend System Design", desc: "Designed frontend systems and maintained UI consistency with responsive experiences.", tag: "UI/UX" },
      { icon: "🔐", title: "Authentication", desc: "Authentication & user management along with freelancer/client onboarding systems.", tag: "Auth" },
      { icon: "📊", title: "Dashboard Infrastructure", desc: "Admin dashboard infrastructure and scalable platform optimization.", tag: "Frontend" },
      { icon: "🤖", title: "AI Automation", desc: "AI workflow and automation integration for operational efficiency.", tag: "AI/ML" },
    ],
    timeline: [
      { year: "2026", type: "project", title: "Connect Freelance", org: "Full Stack Product Development", desc: "Built features like freelancer profiles, hiring workflows, role-based auth, and platform analytics." },
      { year: "2026", type: "project", title: "Freelance Platform UI/UX", org: "Product & Design System Project", desc: "Designed a modern dark-themed SaaS-inspired platform UI using component-based architecture." },
      { year: "2026", type: "project", title: "AI & Automation Workflow", org: "Automation & Productivity Systems", desc: "Explored AI-assisted systems, n8n integrations, and API-based workflow automation." },
      { year: "2026", type: "internship", title: "Engeniuspark Technologies", org: "Full Stack Development Intern", desc: "Worked on real-world full-stack development, API integration, auth systems, and dashboard workflows." },
      { year: "2024-26", type: "education", title: "Diploma in Information Technology", org: "Government Polytechnic, Nashik", desc: "Pursuing diploma with focus on software engineering, database systems, and web technologies." },
      { year: "2024", type: "certification", title: "Full Stack Development Journey", org: "Self Learning & Skill Development", desc: "Deep learning in MERN stack, frontend architecture, backend APIs, and responsive design." },
      { year: "2023", type: "education", title: "SSC Completed", org: "94.00% Percentage", desc: "Developed strong interest in technology, problem-solving, and software systems." },
    ],
    portfolio: [
      { title: "Connect Freelance Features", image: "/ConnectFreelance.png", desc: "Freelancer profile systems, client hiring workflows, dashboard interfaces, responsive landing pages.", techStack: "React.js + Node.js + MongoDB", role: "Product Developer", demo: "https://connectfreelance.in", github: null },
      { title: "Freelance Platform UI/UX", desc: "Component-based UI architecture, reusable layouts, and modern SaaS-inspired dashboard design.", techStack: "Figma + Tailwind CSS", role: "UI/UX Designer", demo: null, github: null },
      { title: "Automation Workflows", desc: "AI-assisted productivity systems, n8n integrations, and API-based smart operational workflows.", techStack: "n8n + APIs", role: "Automation Eng", demo: null, github: null },
    ],
  },
  {
    id: "vaibhav-pawar", name: "Vaibhav Pawar",
    role: "Chief Operations Officer (COO)", shortRole: "Chief Operations Officer",
    tagline: "Operations Lead · Full Stack Developer · Platform Stability",
    img: "/Team-member-5.jpeg", position: "object-[50%_35%]",
    bio1: "Leading operational workflows, platform coordination, testing systems, and quality assurance processes for Connect Freelance. Focused on ensuring smooth collaboration between freelancers and clients while maintaining platform reliability, scalability, and operational efficiency.",
    bio2: "Played a key role in monitoring system performance, workflow management, and maintaining stability across frontend and backend operations. Also contributed to improving user trust, communication workflows, and overall platform consistency.",
    philosophy: "\"Quality is not an act — it's a habit. Ship it only when you'd stake your reputation on it.\"",
    location: "Nashik, Maharashtra, India", experience: "1+", availability: "busy", badgeType: "coo",
    email: "vaibhav@connectfreelance.in", resumeUrl: "/VaibhavPawarResume.pdf", website: "https://portfoliovaibhavpawar.vercel.app/",
    linkedin: "https://www.linkedin.com/in/vaibhav-pawar-3122023b3",
    instagram: "https://www.instagram.com/vaibhav_pawar.96.k",
    facebook: "https://www.facebook.com/share/1BKKwq8ZNQ/",
    github: "https://github.com/vaibhavdpawar9921-Tech",
    aiSummary: "MERN Stack developer and Operations Lead specializing in real-time operational systems, platform scalability, quality assurance, and ground-level workflow management.",
    stats: [{ label: "Deployments Managed", value: 50, suffix: "+" }, { label: "Test Cases Automated", value: 120, suffix: "+" }, { label: "Features Shipped", value: 30, suffix: "+" }, { label: "Uptime Monitored", value: 99, suffix: "%" }],
    skills: [
      { name: "React.js", level: 88, category: "Frontend" }, { name: "Node.js", level: 85, category: "Backend" }, { name: "Express.js", level: 85, category: "Backend" },
      { name: "MongoDB", level: 82, category: "Database" }, { name: "QA & Testing", level: 90, category: "DevOps" },
      { name: "System Architecture", level: 85, category: "Backend" }, { name: "Operations Management", level: 92, category: "Product" },
    ],
    contributions: [
      { icon: "🛠️", title: "MERN Stack Dev", desc: "Developed authentication, role-based systems, and dashboard workflows.", tag: "Full Stack" },
      { icon: "💳", title: "Platform Economics", desc: "Implemented Membership plan management, Connect Credit allocation, and Wallet tracking.", tag: "Backend" },
      { icon: "⚙️", title: "Operations & Stability", desc: "Managed platform testing, quality assurance, performance optimization, and ground-level workflow.", tag: "QA & Ops" },
      { icon: "🤝", title: "User Workflows", desc: "Coordinated client and freelancer communication, real-time operations, and trust-focused infrastructure.", tag: "Product" },
    ],
    timeline: [
      { year: "2026", type: "project", title: "Connect Freelance", org: "Chief Operations Officer (COO)", desc: "Leading operational workflows, platform coordination, testing systems, and quality assurance processes for Connect Freelance." },
      { year: "2025", type: "internship", title: "Full Stack Development Intern", org: "Engeniuspark Technologies Pvt. Ltd.", desc: "Worked on full-stack web application development using modern MERN stack technologies. Collaborated on frontend interfaces, backend APIs, and DB management." },
      { year: "2025", type: "project", title: "The Perfect Home", org: "Full Stack Real Estate Platform", desc: "Developed a modern real-estate web platform for online property discovery, listing management, and home purchasing workflows." },
      { year: "2025", type: "project", title: "Waste Detection System", org: "Machine Learning & Computer Vision", desc: "Developed an intelligent waste classification system for detecting plastic and paper materials using machine learning." },
      { year: "2024", type: "education", title: "Diploma in IT", org: "Government Polytechnic, Nashik", desc: "Pursuing diploma studies focused on practical software engineering, database systems, programming logic, and modern web technologies." },
      { year: "2024", type: "certification", title: "Full Stack Journey", org: "Self Learning", desc: "Deep learning in full-stack development and modern software technologies while building practical projects." },
      { year: "2023", type: "education", title: "SSC Completed", org: "94.40%", desc: "Built a strong academic foundation while developing interest in software systems and modern technology platforms." },
    ],
    portfolio: [
      { title: "Connect Freelance", image: "/ConnectFreelance.png", desc: "Leading operational workflows, platform coordination, testing systems, and QA processes. Worked on MERN stack features, wallet tracking, and role-based systems.", techStack: "MERN + QA", role: "Chief Operations Officer", demo: "https://connectfreelance.in", github: null },
      { title: "The Perfect Home", image: "/ThePerfectHome.jpeg", desc: "A full-stack online real estate broker platform where builders list properties and buyers browse, explore, and submit purchase inquiries.", techStack: "HTML/CSS + JS + PHP + MySQL", role: "Full Stack Developer", demo: "https://lavender-donkey-922858.hostingersite.com/Builders/index.php", github: null },
      { title: "Waste Detection System", image: null, desc: "An intelligent waste classification system for detecting plastic and paper materials using machine learning and computer vision techniques to automate recycling.", techStack: "Python + TensorFlow + OpenCV", role: "ML Developer", demo: null, github: null },
      { title: "Personal Portfolio", image: null, desc: "A modern personal portfolio website to showcase projects, technical skills, internship experience, and full-stack development work with an optimized responsive interface.", techStack: "React.js + Tailwind CSS", role: "Full Stack Developer", demo: "https://portfoliovaibhavpawar.vercel.app/", github: null },
    ],
  },
];
