export const ROLES = {
    CLIENT: 'CLIENT',
    FREELANCER: 'FREELANCER',
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    MODERATOR: 'MODERATOR',
    FINANCE_ADMIN: 'FINANCE_ADMIN',
    SUPPORT_ADMIN: 'SUPPORT_ADMIN'
};

export const ADMIN_ROLES = [
    ROLES.SUPER_ADMIN,
    ROLES.ADMIN,
    ROLES.MODERATOR,
    ROLES.FINANCE_ADMIN,
    ROLES.SUPPORT_ADMIN
];
